env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
  - 'plugin:vue/base'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: vue-eslint-parser
parserOptions: {
    parser: babel-eslint,
    ecmaVersion: 2020,
    sourceType: module
}
plugins:
  - vue
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - always
